'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');
const mod=()=>import('file://'+path.resolve(__dirname,'../public/gametwin-director.mjs'));

test('v1.9 director builds a multi-shot HR timeline with landing coverage',async()=>{const d=await mod();assert.equal(d.GAMETWIN_DIRECTOR_VERSION,'1.9.0');const e={kind:'plate_appearance',outcome:'HR',leverage:.91,batted_ball:{distance_ft:431,spray_angle_deg:18},scored:['A']};const t=d.eventCameraTimeline(e);assert.ok(t.find(x=>x.phase==='contact'&&x.camera==='batter'));assert.ok(t.find(x=>x.phase==='flight'&&x.camera==='ball_track'));assert.ok(t.find(x=>x.phase==='landing'&&x.camera==='outfield_wall'));assert.ok(t.find(x=>x.phase==='crowd'&&x.camera==='stadium'));assert.equal(t.every(x=>x.presentation_only),true);});

test('v1.9 close-play timeline holds the relevant base camera',async()=>{const d=await mod();const e={kind:'plate_appearance',outcome:'1B',batted_ball:{},leverage:.78,close_play:{active:true,base:3}};const t=d.eventCameraTimeline(e);assert.equal(t.find(x=>x.phase==='runner').camera,'base_3');assert.equal(t.find(x=>x.phase==='finish').camera,'base_3');});

test('v1.9 runner/throw race plan is bounded and never owns the verdict',async()=>{const d=await mod();const p=d.runnerThrowRacePlan({leverage:.9,close_play:{active:true,visual_margin_s:.18}});assert.ok(p.runner_speed_multiplier>.8&&p.runner_speed_multiplier<1.4);assert.ok(p.throw_speed_multiplier>.8&&p.throw_speed_multiplier<1.4);assert.equal(p.verdict_source,'simulation_state_only');assert.equal(p.presentation_only,true);});

test('v1.9 replay engine gives HR three passes and close play two',async()=>{const d=await mod();const hr=d.replayPasses({outcome:'HR',replay:{eligible:true},batted_ball:{}});assert.deepEqual(hr.map(x=>x.segment),['pitch_contact','flight','reaction']);const cp=d.replayPasses({outcome:'1B',replay:{eligible:true},close_play:{active:true,base:2}});assert.deepEqual(cp.map(x=>x.segment),['race','tag']);assert.equal(cp[0].camera,'base_2');});

test('v1.9 replay respects ineligible replay cue',async()=>{const d=await mod();assert.deepEqual(d.replayPasses({outcome:'OUT',replay:{eligible:false}}),[]);});

test('v1.9 transition policy uses cuts for replay/base action and easing for wide shots',async()=>{const d=await mod();assert.equal(d.transitionFor({from:'broadcast',to:'base_2'}).style,'cut');assert.equal(d.transitionFor({from:'batter',to:'stadium'}).style,'ease');assert.equal(d.transitionFor({from:'broadcast',to:'ball_track',replay:true}).style,'cut');});

test('v1.9 HR landing shot is presentation-only and direction aware',async()=>{const d=await mod();const s=d.landingShot({outcome:'HR',batted_ball:{spray_angle_deg:-22,distance_ft:442}});assert.equal(s.side,'left');assert.equal(s.camera,'outfield_wall');assert.equal(s.presentation_only,true);});

test('v1.9 broadcast exposes replay/director features without predictive authority',()=>{const b=require('../src/gametwin-broadcast');const row={broadcast_context:{gamePk:1,date:'2026-09-04T23:00:00Z',venue:{name:'Park',field:{}},weather:{},away:{name:'Away',lineup:[],starter:{name:'A',arsenal:[]},bullpen:[]},home:{name:'Home',lineup:[],starter:{name:'H',arsenal:[]},bullpen:[]}},representative_game:{final:{away:0,home:0},play_by_play:[]}};const out=b.buildBroadcast(row),c=out.capabilities;assert.equal(c.visual_fidelity_version,'1.9.0');assert.equal(c.cinematic_gameplay_version,'1.8.0');assert.equal(c.broadcast_director_version,'1.9.0');assert.equal(c.event_camera_timelines,true);assert.equal(c.multi_pass_replay_engine,true);assert.equal(c.runner_throw_race_synchronization,true);assert.equal(c.photorealistic_players,false);assert.equal(out.presentation_only,true);});

test('v1.9 hosted renderer wires director timelines, synchronized close-play race and multi-pass replay',()=>{const fs=require('node:fs'),path=require('node:path');const src=fs.readFileSync(path.resolve(__dirname,'../public/gametwin-3d.mjs'),'utf8');assert.match(src,/gametwin-director\.mjs\?v=1\.9\.0/);assert.match(src,/animateRunnerThrowRace/);assert.match(src,/replayPasses\(e\)/);assert.match(src,/animateReplayPass/);assert.match(src,/plate_low/);assert.match(src,/outfield_wall/);assert.doesNotMatch(src,/runSimulations|release_eligible\s*=\s*true|aegis_weight\s*=\s*[1-9]/);});

test('v1.9 WATCH UI surfaces replay state without changing analysis or prediction data',()=>{const fs=require('node:fs'),path=require('node:path');const src=fs.readFileSync(path.resolve(__dirname,'../public/gametwin-production-ui.js'),'utf8');assert.match(src,/gametwin:replay-start/);assert.match(src,/gametwin:replay-pass/);assert.match(src,/gametwin:replay-end/);assert.match(src,/REPLAY/);assert.match(src,/LIVE SIM/);});
