'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');const {pathToFileURL}=require('url');
const root=path.join(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');

test('v1.7 asset descriptors choose quality-aware LODs with safe fallback',async()=>{const m=await import(pathToFileURL(path.join(root,'public/gametwin-assets.mjs')).href+'?v='+Date.now());const d={url:'/base.glb',lods:{low:'/low.glb',medium:'/med.glb',high:'/high.glb'}};assert.equal(m.chooseAssetUrl(d,'low'),'/low.glb');assert.equal(m.chooseAssetUrl(d,'medium'),'/med.glb');assert.equal(m.chooseAssetUrl(d,'high'),'/high.glb');assert.equal(m.chooseAssetUrl({url:'/one.glb'},'high'),'/one.glb');});

test('v1.7 asset budgets protect mobile and permit larger high-quality models',async()=>{const m=await import(pathToFileURL(path.join(root,'public/gametwin-assets.mjs')).href+'?v=budgets');assert.ok(m.triangleBudget('batter','low')<m.triangleBudget('batter','high'));assert.ok(m.triangleBudget('generic_stadium','low')<m.triangleBudget('generic_stadium','high'));assert.equal(m.triangleBudget('batter','medium',{max_triangles:{medium:12345}}),12345);});

test('v1.7 scene validator rejects over-budget geometry and reports missing animation contracts',async()=>{const m=await import(pathToFileURL(path.join(root,'public/gametwin-assets.mjs')).href+'?v=validate');const rootObj={traverse(fn){fn({isMesh:true,isSkinnedMesh:true,geometry:{index:{count:300000}},material:null});}};const out=m.validateAssetScene(rootObj,{kind:'batter',quality:'low',descriptor:{max_triangles:{low:1000},required_animations:['idle','swing']},animations:[{name:'idle'}]});assert.equal(out.ok,false);assert.match(out.errors.join(','),/triangle_budget_exceeded/);assert.match(out.warnings.join(','),/missing_animation:swing/);});

test('v1.7 manifest example contains separate LOD and animation contracts for all baseball roles',()=>{const s=read('public/gametwin-asset-manifest.example.js');for(const role of ['batter','pitcher','fielder','runner','catcher','umpire'])assert.match(s,new RegExp(`${role}:\\{`));assert.match(s,/lods:\{low:null,medium:null,high:null\}/);assert.match(s,/required_animations/);assert.match(s,/max_triangles/);});

test('v1.7 3D scene preloads quality-validated assets and retains fallback',()=>{const s=read('public/gametwin-3d.mjs');assert.match(s,/assets\.preload/);assert.match(s,/gametwinAssetValidation/);assert.match(s,/target_height_ft/);assert.match(s,/rig\.hips\.visible=false/);assert.match(s,/asset_lod_selection:true/);assert.match(s,/asset_budget_validation:true/);});

test('v1.7 broadcast advertises asset runtime governance without false photorealism',()=>{const b=require('../src/gametwin-broadcast');const row={broadcast_context:{gamePk:1,date:'2026-09-04T23:00:00Z',venue:{name:'Park',field:{}},weather:{},away:{name:'Away',lineup:[],starter:{name:'A',arsenal:[]},bullpen:[]},home:{name:'Home',lineup:[],starter:{name:'H',arsenal:[]},bullpen:[]}},representative_game:{final:{away:0,home:0},play_by_play:[]}};const c=b.buildBroadcast(row).capabilities;assert.equal(c.visual_fidelity_version,'1.9.0');assert.equal(c.asset_lod_selection,true);assert.equal(c.asset_triangle_budget_validation,true);assert.equal(c.asset_animation_contract_validation,true);assert.equal(c.photorealistic_players,false);assert.equal(c.licensed_stadium_asset_models,false);});
