'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
function read(name){return fs.readFileSync(path.join(__dirname,'..','public',name),'utf8');}
test('GameTwin v2.0 production shadow lab remains shadow-only and keeps Canvas fallback',()=>{const html=read('gametwin.html'),ui=read('gametwin-ui.js'),visual=read('gametwin-broadcast.js'),loader=read('gametwin-3d-loader.js');assert.match(html,/GameTwin v(?:1\.(?:0(?:\.1|\.2)?|1\.0|2\.0|3\.0|4\.0|5\.0|6\.0|7\.0|8\.0|9\.0)|2\.0\.0) Production Shadow Lab|GameTwin v2\.1\.0 Deployment-Ready Shadow Lab/);assert.match(html,/AEGIS weight 0%/);assert.match(html,/gametwin-broadcast\.js/);assert.match(html,/gametwin-3d-loader\.js/);assert.match(ui,/makeBroadcastScene/);assert.match(ui,/Canvas2D fallback/);assert.match(ui,/cameraMode/);assert.match(ui,/qualityMode/);assert.match(ui,/crowdSound/);assert.match(ui,/instantReplay/);assert.match(ui,/replayLast/);assert.match(ui,/AEGIS Auto camera/);assert.match(visual,/GameTwinBroadcastScene/);assert.match(loader,/GameTwin3DReady/);});
test('3D loader pins Three.js and requires WebGL2 before enabling renderer',()=>{const loader=read('gametwin-3d-loader.js');assert.match(loader,/three@0\.185\.1\/build\/three\.module\.min\.js/);assert.match(loader,/WebGL2RenderingContext/);assert.match(loader,/FALLBACK/);assert.match(loader,/GameTwinBroadcastScene3D/);});
test('Three.js scene uses articulated player rigs and real 3D renderer constructs',()=>{const src=read('gametwin-3d.mjs');assert.match(src,/class PlayerRig extends THREE\.Group/);assert.match(src,/new THREE\.WebGLRenderer/);assert.match(src,/CapsuleGeometry/);assert.match(src,/pitch_set/);assert.match(src,/pitch_lift/);assert.match(src,/pitch_drive/);assert.match(src,/swing_load/);assert.match(src,/swing_contact/);assert.match(src,/blendPose\(slide\?'slide':finish\.clip/);assert.match(src,/PerspectiveCamera/);assert.match(src,/wallPoint/);assert.match(src,/fieldDimensions/);assert.match(src,/parkProfileSummary/);assert.match(src,/animateFieldingAction/);assert.match(src,/toggleCrowd/);assert.match(src,/setQuality/);assert.match(src,/applyAutoCamera/);assert.match(src,/animateRelayPlan/);assert.match(src,/animateClosePlay/);assert.match(src,/replayEvent/);assert.match(src,/reactCrowd/);});

test('Command Center integration embeds GameTwin inside MLB Game Lab with pilot controls and inline 3D',()=>{const js=read('gametwin-command-center.js'),css=read('gametwin-command-center.css');assert.match(js,/WATCH \/ ANALYZE SHADOW PILOT/);assert.match(js,/api\/gametwin\/overview/);assert.match(js,/pilot\/pause/);assert.match(js,/pilot\/resume/);assert.match(js,/pilot\/reset/);assert.match(js,/makeInlineScene/);assert.match(js,/GameTwinBroadcastScene3D/);assert.match(js,/Watch 3D here/);assert.match(js,/Open WATCH \/ ANALYZE/);assert.match(css,/gametwinIntegratedLab/);assert.match(css,/gtcc-stage/);});

test('GameTwin lab loads fallback mobile UX plus production WATCH ANALYZE shell',()=>{const html=read('gametwin.html');assert.match(html,/gametwin-mobile-ux\.js/);assert.match(html,/gametwin-production-ui\.js/);assert.match(html,/gametwin-production\.css/);const ui=read('gametwin-ui.js');assert.match(ui,/GameTwinBroadcastController/);assert.match(ui,/gametwin:broadcast-ready/);assert.match(ui,/prevPA/);assert.match(ui,/seekBroadcast/);});
