'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {createDashboardService,familyFilteredSnapshots}=require('../src/gametwin-dashboard');
test('family filter keeps only graded forecasts from requested market family',()=>{const rows=[{grade:{status:'FINAL',forecasts:[{family:'moneyline',grade_status:'GRADED',outcome:'WIN',fair_probability:.6,brier:.16},{family:'total',grade_status:'GRADED',outcome:'LOSS',fair_probability:.55,brier:.3025}]}}];const x=familyFilteredSnapshots(rows,'moneyline');assert.equal(x.length,1);assert.equal(x[0].grade.forecasts.length,1);assert.equal(x[0].grade.forecasts[0].family,'moneyline');});
test('dashboard status exposes zero-weight governance',async()=>{const runtime={VERSION:'rt',auditStore:{list:async()=>[]},stateStore:{status:async()=>({runtime:{state:'IDLE'},errors:[]}),latestSlate:async()=>null,game:async()=>null}};const d=createDashboardService({runtime}),s=await d.status();assert.equal(s.aegis_weight,0);assert.equal(s.release_eligible,false);assert.equal(s.calibration.governance.aegis_weight,0);});

test('dashboard game endpoint emits presentation-only broadcast timeline',async()=>{const row={gamePk:1,away:'A',home:'H',venue:'Park',weather:{},broadcast_context:{gamePk:1,venue:{name:'Park',field:{center:400}},weather:{},away:{name:'A',lineup:[{name:'AB'}],starter:{name:'ASP',arsenal:[]},bullpen:[]},home:{name:'H',lineup:[{name:'HB'}],starter:{name:'HSP',arsenal:[]},bullpen:[]}},representative_game:{final:{away:0,home:0},play_by_play:[{inning:1,half:'top',pa_number:1,batter:'AB',pitcher:'HSP',outcome:'K',pitch_count:3,outs_before:0,outs_after:1,scored:[],bases:[null,null,null]}]}};const runtime={VERSION:'rt',auditStore:{list:async()=>[]},stateStore:{status:async()=>({runtime:{state:'IDLE'},errors:[]}),latestSlate:async()=>null,game:async()=>row}};const d=createDashboardService({runtime}),g=await d.game(1);assert.equal(g.broadcast.presentation_only,true);assert.ok(g.broadcast.events.some(e=>e.kind==='plate_appearance'));});

test('dashboard exposes same-market GameTwin vs AEGIS vs market moneyline comparison',async()=>{const row={gamePk:2,away:'Away Club',home:'Home Club',win_probability:{away:.46,home:.54},broadcast_context:{gamePk:2,venue:{name:'Park',field:{center:400}},weather:{},away:{name:'Away Club',lineup:[],starter:{name:'ASP',arsenal:[]},bullpen:[]},home:{name:'Home Club',lineup:[],starter:{name:'HSP',arsenal:[]},bullpen:[]}},representative_game:{final:{away:2,home:3},play_by_play:[]}};const snaps=[{gamePk:2,snapshot_id:'s1',captured_at:'2026-09-04T12:00:00Z',forecasts:[{family:'moneyline',fair_probability:.54,aegis_probability:.51,market_devig_probability:.505,quote:{selection:'Home Club',price:-110,book:'Hard Rock'}}]}];const runtime={VERSION:'rt',auditStore:{list:async()=>snaps},stateStore:{status:async()=>({runtime:{state:'IDLE'},errors:[]}),latestSlate:async()=>null,game:async()=>row}};const d=createDashboardService({runtime}),g=await d.game(2);assert.equal(g.model_comparison.available,true);assert.equal(g.model_comparison.home.gametwin,.54);assert.equal(g.model_comparison.home.aegis,.51);assert.equal(g.model_comparison.home.market,.505);assert.ok(Math.abs(g.model_comparison.away.gametwin-.46)<1e-12);assert.equal(g.game.model_comparison.book,'Hard Rock');});

test('dashboard game response includes normalized WATCH ANALYZE view model',async()=>{const row={gamePk:3,away:'Atlanta Braves',home:'Washington Nationals',simulations:25000,projected_score:{away:5.2,home:4.1,total:9.3},win_probability:{away:.58,home:.42},markets:{over_8_5:.55,under_8_5:.45},broadcast_context:{gamePk:3,venue:{name:'Park',field:{center:400}},weather:{temperature_f:78},away:{name:'Atlanta Braves',lineup:[],starter:{name:'ASP',arsenal:[]},bullpen:[]},home:{name:'Washington Nationals',lineup:[],starter:{name:'HSP',arsenal:[]},bullpen:[]}},representative_game:{final:{away:5,home:4},play_by_play:[]}};const runtime={VERSION:'rt',auditStore:{list:async()=>[]},stateStore:{status:async()=>({runtime:{state:'IDLE'},errors:[]}),latestSlate:async()=>null,game:async()=>row}};const d=createDashboardService({runtime}),g=await d.game(3);assert.equal(g.view_model.version,'1.7.0-watch-analyze-viewmodel');assert.equal(g.view_model.game.simulations,25000);assert.equal(g.view_model.governance.aegis_weight,0);assert.equal(g.view_model.governance.release_eligible,false);assert.ok(g.view_model.watch);assert.ok(g.view_model.analyze);});
