'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const b=require('../src/gametwin-broadcast');
function sample(){return {gamePk:99,away:'Away',home:'Home',venue:'Test Park',weather:{temperature_f:81,wind_mph:12},broadcast_context:{gamePk:99,venue:{name:'Test Park',field:{left_line:310,left_center:370,center:410,right_center:365,right_line:325,roof:'Open'}},weather:{temperature_f:81,wind_mph:12},away:{name:'Away',lineup:[{name:'A Batter',avg_exit_velocity:92}],starter:{name:'Away SP',arsenal:[{pitch_type:'FF',usage:.6},{pitch_type:'SL',usage:.4}]},bullpen:[]},home:{name:'Home',lineup:[{name:'H Batter',avg_exit_velocity:90}],starter:{name:'Home SP',arsenal:[{pitch_type:'SI',usage:.5},{pitch_type:'CH',usage:.5}]},bullpen:[]}},representative_game:{final:{away:1,home:0},play_by_play:[{inning:1,half:'top',pa_number:1,batter:'A Batter',pitcher:'Home SP',outcome:'HR',pitch_count:4,outs_before:0,outs_after:0,scored:['A Batter'],bases:[null,null,null]},{inning:1,half:'bottom',pa_number:1,batter:'H Batter',pitcher:'Away SP',outcome:'K',pitch_count:3,outs_before:0,outs_after:1,scored:[],bases:[null,null,null]}]}};}
test('field dimensions preserve MLB venue geometry when supplied',()=>{const f=b.fieldDimensions({fieldInfo:{leftLine:302,leftCenter:368,center:399,rightCenter:376,rightLine:314,roofType:'Retractable Roof',turfType:'Grass'}});assert.equal(f.left_line,302);assert.equal(f.center,399);assert.equal(f.right_line,314);assert.equal(f.roof,'Retractable Roof');});
test('broadcast choreography is deterministic and presentation only',()=>{const a=b.buildBroadcast(sample()),c=b.buildBroadcast(sample());assert.deepEqual(a,c);assert.equal(a.presentation_only,true);assert.equal(a.capabilities.actual_field_dimensions,true);});
test('plate appearance pitch choreography respects simulated pitch count',()=>{const x=b.buildBroadcast(sample()),pa=x.events.find(e=>e.kind==='plate_appearance');assert.equal(pa.pitch_count,4);assert.equal(pa.pitches.length,4);assert.equal(pa.pitches.at(-1).result,'in_play');assert.ok(pa.batted_ball.distance_ft>=365);});
test('broadcast scoreboard advances from simulated scoring only',()=>{const x=b.buildBroadcast(sample()),pas=x.events.filter(e=>e.kind==='plate_appearance');assert.deepEqual(pas[0].score,{away:1,home:0,inning:1,half:'top'});assert.deepEqual(pas[1].score,{away:1,home:0,inning:1,half:'bottom'});});
test('runner move builder advances batter to scored home on home run',()=>{const moves=b.runnerMoves([null,null,null],[null,null,null],['Slugger'],'Slugger','HR');assert.deepEqual(moves,[{name:'Slugger',from:0,to:4}]);});
test('v0.9 broadcast advertises physics and broadcast intelligence without granting predictive authority',()=>{const x=b.buildBroadcast(sample());assert.equal(x.presentation_only,true);assert.equal(x.capabilities.true_3d,true);assert.equal(x.capabilities.render_engine,'Three.js 0.185.1');assert.equal(x.capabilities.articulated_player_rigs,true);assert.equal(x.capabilities.webgl2_fallback,true);assert.equal(x.capabilities.park_identity_profiles,true);assert.equal(x.capabilities.fielder_pursuit,true);assert.equal(x.capabilities.throw_choreography,true);assert.equal(x.capabilities.outcome_constrained_ball_physics,true);assert.equal(x.capabilities.wall_collisions,true);assert.equal(x.capabilities.relay_throws,true);assert.equal(x.capabilities.leverage_camera_director,true);assert.equal(x.capabilities.instant_replay_cues,true);assert.deepEqual(x.capabilities.mobile_quality_tiers,['auto','low','medium','high']);assert.equal(x.capabilities.day_night_lighting,true);assert.equal(x.capabilities.photorealistic_players,false);});

test('fielding choreography chooses a defender and remains presentation-only',()=>{const x=b.buildBroadcast(sample()),pa=x.events.find(e=>e.kind==='plate_appearance');assert.ok(pa.fielding_action);assert.equal(pa.fielding_action.presentation_only,true);assert.ok(['LF','CF','RF','1B','2B','SS','3B'].includes(pa.fielding_action.fielder_slot));});

test('plate appearances carry outcome-constrained flight, camera, crowd and replay metadata',()=>{const x=b.buildBroadcast(sample()),pa=x.events.find(e=>e.kind==='plate_appearance');assert.ok(pa.ball_flight);assert.equal(pa.ball_flight.outcome_constrained,true);assert.ok(pa.camera_plan?.auto);assert.ok(Number.isFinite(pa.leverage));assert.equal(pa.crowd_reaction.presentation_only,true);assert.equal(pa.replay.presentation_only,true);});
test('broadcast renders explicit steal events without synthesizing them',()=>{const s=sample();s.representative_game.play_by_play.unshift({type:'steal',inning:1,half:'top',runner:'Runner X',from_base:1,to_base:2,success:true,outs_before:0});const x=b.buildBroadcast(s),st=x.events.find(e=>e.kind==='steal_attempt');assert.ok(st);assert.equal(st.runner,'Runner X');assert.equal(st.success,true);assert.equal(st.presentation_only,true);});
