'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {patchServerText,patchIndexText,preflight}=require('../scripts/install-into-aegis-v8.9.3');
const fixture=`const store = require('./src/store');\nconst heartbeat = require('./src/heartbeat');\nconst server=http.createServer(async(req,res)=>{\n  try{\n    const u=new URL(req.url,\`http://\${req.headers.host||'localhost'}\`);\n    if(req.method==='POST'&&u.pathname==='/api/autopilot/tick'){\n      const body=JSON.parse(await readBody(req)||'{}'),sport=u.searchParams.get('sport')||body.sport||null,force=u.searchParams.get('force')==='1'||!!body.force;\n      const result=await autopilot.tick({force,sports:sport?[sport]:body.sports,reason:body.reason||'scheduled autopilot'});\n      return send(res,200,result);\n    }\n      try{out.persistence=await autopilot.captureScan(sport,out,events,'manual in-depth scan');}catch(e){out.persistence={saved:false,error:e.message};}\n      return send(res,200,out);\n  }catch(e){}\n});`;
test('v8.9.3 installer adds API, scheduled and manual hooks exactly once',()=>{const once=patchServerText(fixture),twice=patchServerText(once);assert.match(once,/createGameTwinService/);assert.match(once,/GAMETWIN API HOOK/);assert.match(once,/GAMETWIN AUTOPILOT HOOK/);assert.match(once,/GAMETWIN MANUAL-SCAN HOOK/);assert.equal(twice,once);});
test('v2.1.0 installer permits pinned Three.js origin while preserving self scripts',()=>{const input=fixture.replace("const server=http.createServer","const SECURITY_HEADERS = {'Content-Security-Policy':\"default-src 'self'; script-src 'self'; connect-src 'self'\"};\nconst server=http.createServer");const out=patchServerText(input);assert.match(out,/script-src 'self' https:\/\/unpkg\.com\/three@0\.185\.1\//);});

test('v2.1.0 installer patches Command Center index exactly once',()=>{const input='<html><head><title>AEGIS</title></head><body><section id="lab"></section></body></html>';const once=patchIndexText(input),twice=patchIndexText(once);assert.match(once,/gametwin-command-center\.css\?v=2\.1\.0/);assert.match(once,/gametwin-broadcast\.js\?v=2\.1\.0/);assert.match(once,/gametwin-asset-manifest\.js\?v=2\.1\.0/);assert.match(once,/gametwin-3d-loader\.js\?v=2\.1\.0/);assert.match(once,/gametwin-command-center\.js\?v=2\.1\.0/);assert.equal(twice,once);});
test('v2.1.0 installer performs guarded local install with rollback backups',()=>{const fs=require('fs'),os=require('os'),path=require('path');const {install}=require('../scripts/install-into-aegis-v8.9.3');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gt-v1-install-'));fs.mkdirSync(path.join(dir,'public'),{recursive:true});fs.mkdirSync(path.join(dir,'src'),{recursive:true});fs.mkdirSync(path.join(dir,'tests'),{recursive:true});fs.writeFileSync(path.join(dir,'package.json'),JSON.stringify({version:'8.9.3'}));fs.writeFileSync(path.join(dir,'server.js'),fixture);fs.writeFileSync(path.join(dir,'public','index.html'),'<html><head></head><body><section id="lab"></section></body></html>');const out=install(dir);assert.equal(out.integrated_game_lab,true);assert.equal(out.aegis_weight,0);assert.ok(fs.existsSync(path.join(dir,'src','gametwin-pilot.js')));assert.ok(fs.existsSync(path.join(dir,'public','gametwin-command-center.js')));assert.ok(fs.existsSync(path.join(dir,'public','gametwin-demo-data.js')));assert.ok(fs.existsSync(path.join(dir,'public','gametwin-asset-manifest.js')));assert.ok(fs.existsSync(path.join(dir,'public','gametwin-assets','characters','batter-low.glb')));assert.ok(fs.existsSync(path.join(dir,'server.js.pre-gametwin-v1.0.bak')));assert.ok(fs.existsSync(path.join(dir,'public','index.html.pre-gametwin-v1.0.bak')));const second=install(dir);assert.equal(second.server_patched,false);assert.equal(second.index_patched,false);fs.rmSync(dir,{recursive:true,force:true});});

test('v2.1.0 installer preflight is read-only and validates AEGIS 8.9.3 anchors',()=>{const fs=require('fs'),os=require('os'),path=require('path');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gt-v21-preflight-'));fs.mkdirSync(path.join(dir,'public'),{recursive:true});fs.writeFileSync(path.join(dir,'package.json'),JSON.stringify({version:'8.9.3'}));fs.writeFileSync(path.join(dir,'server.js'),fixture);fs.writeFileSync(path.join(dir,'public','index.html'),'<html><head></head><body></body></html>');const before=fs.readFileSync(path.join(dir,'server.js'),'utf8');const out=preflight(dir);assert.equal(out.compatible,true);assert.equal(out.write_performed,false);assert.equal(out.aegis_weight,0);assert.equal(fs.readFileSync(path.join(dir,'server.js'),'utf8'),before);fs.rmSync(dir,{recursive:true,force:true});});
