'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {createProductionShadowRuntime,closingQuotesFromAuditRows}=require('../src/gametwin-runtime');
function lineup(prefix){return Array.from({length:9},(_,i)=>({id:i+1,name:`${prefix}${i+1}`,pa:{K:.22,BB:.09,HBP:.01,'1B':.16,'2B':.05,'3B':.004,HR:.032,OUT:.434}}));}
function spec(){return {gamePk:99,date:'2026-09-04T23:00:00Z',away:{name:'Atlanta Braves',lineup:lineup('A'),starter:{name:'Away SP',max_innings:5},bullpen:[{name:'Away RP'}]},home:{name:'Washington Nationals',lineup:lineup('H'),starter:{name:'Home SP',max_innings:5},bullpen:[{name:'Home RP'}]},venue:{name:'Nationals Park'},environment:{run_factor:1,hr_factor:1,verified:true},lineups_confirmed:true,probable_starters_confirmed:true,bullpen_verified:true,data_quality:{lineups:'confirmed'}};}
function card(){return {version:'8.9.3',generated_at:'2026-09-04T20:00:00Z',analyses:[{event:{id:'e1',sport_key:'baseball_mlb',away_team:'Atlanta Braves',home_team:'Washington Nationals',commence_time:'2026-09-04T23:00:00Z'},market:{all:[{market:'h2h',selection:'Atlanta Braves',price:-140,book:'Hard Rock',book_key:'hardrockbet_fl',hard_rock:true,fair_probability:.61},{market:'h2h',selection:'Washington Nationals',price:+120,book:'Hard Rock',book_key:'hardrockbet_fl',hard_rock:true,fair_probability:.39}]}}]};}
function store(){let state={audit:[],latest_cards:{}};return {async load(){return structuredClone(state);},async mutate(fn){const w=structuredClone(state);const result=await fn(w);state=w;return {state,result};},peek(){return state;}};}
test('production runtime records one canonical confirmed-lineup shadow snapshot and saves latest slate',async()=>{const a=store(),client={slate:async()=>[{gamePk:99}],buildGameSpec:async()=>spec()},resultsClient={finalResult:async()=>({final:false,status:'Preview'})},rt=createProductionShadowRuntime({aegisStore:a,dataClient:client,resultsClient,simulations:80,gradeIntervalMs:9999999});const r=await rt.processCard(card());assert.equal(r.summary.ready,1);assert.equal((await rt.auditStore.list()).length,1);assert.equal((await rt.stateStore.latestSlate()).games[0].gamePk,99);const r2=await rt.processCard(card());assert.equal(r2.skipped,true);assert.equal((await rt.auditStore.list()).length,1);});
test('queued GameTwin failure cannot throw into AEGIS flow',async()=>{const a=store(),client={slate:async()=>[{gamePk:99}],buildGameSpec:async()=>{throw new Error('GameTwin data failed');}},rt=createProductionShadowRuntime({aegisStore:a,dataClient:client,resultsClient:{finalResult:async()=>({final:false})},simulations:50});const q=rt.queueCard(card());assert.equal(q.queued,true);const r=await rt.drain();assert.match(r.error,/failed for every MLB game/);const st=await rt.stateStore.status();assert.equal(st.aegis_weight,0);const ps=await rt.pilot.status();assert.equal(ps.failed_runs,1);assert.equal(ps.circuit,'CLOSED');});
test('closing quote adapter uses latest pregame AEGIS market-history snapshot',()=>{const snapshot={teams:{away:'Atlanta Braves',home:'Washington Nationals'},game_date:'2026-09-04T23:00:00Z',forecasts:[{quote:{market:'moneyline',selection:'Atlanta Braves',price:-140}}]},rows=[{sport_key:'baseball_mlb',away_team:'Atlanta Braves',home_team:'Washington Nationals',commence_time:'2026-09-04T23:00:00Z',market:'h2h',selection:'Atlanta Braves',point:null,snapshots:[{at:'2026-09-04T21:00:00Z',price:-145},{at:'2026-09-04T22:50:00Z',price:-155},{at:'2026-09-04T23:10:00Z',price:-160}]}];const q=closingQuotesFromAuditRows(rows,snapshot);assert.equal(q[0].price,-155);});

test('duplicate card skips resimulation but still checks automatic grading cadence',async()=>{const a=store(),client={slate:async()=>[{gamePk:99}],buildGameSpec:async()=>spec()};let resultCalls=0;const resultsClient={finalResult:async()=>{resultCalls++;return {final:false,status:'Preview'};}};const rt=createProductionShadowRuntime({aegisStore:a,dataClient:client,resultsClient,simulations:40,gradeIntervalMs:5});await rt.processCard(card());await a.mutate(state=>{state.gametwin.runtime.last_grade_at='2026-09-04T00:00:00Z';});const before=resultCalls;const second=await rt.processCard(card());assert.equal(second.skipped,true);assert.ok(resultCalls>before);});
test('production pilot circuit breaker stops repeated catastrophic shadow failures',async()=>{const a=store();let calls=0;const client={slate:async()=>[{gamePk:99}],buildGameSpec:async()=>{calls++;throw new Error('upstream hard fail');}};const rt=createProductionShadowRuntime({aegisStore:a,dataClient:client,resultsClient:{finalResult:async()=>({final:false})},simulations:20,pilotOptions:{maxConsecutiveFailures:2,cooldownMinutes:120}});await rt.processCard(card(),{force:true});await rt.processCard({...card(),generated_at:'2026-09-04T20:01:00Z'},{force:true});const ps=await rt.pilot.status();assert.equal(ps.circuit,'OPEN');const before=calls;const third=await rt.processCard({...card(),generated_at:'2026-09-04T20:02:00Z'},{force:true});assert.equal(third.skipped,true);assert.equal(third.reason,'circuit breaker open');assert.equal(calls,before);});
test('paused production pilot skips GameTwin work without touching AEGIS flow',async()=>{const a=store();let calls=0;const client={slate:async()=>{calls++;return [{gamePk:99}]},buildGameSpec:async()=>spec()};const rt=createProductionShadowRuntime({aegisStore:a,dataClient:client,resultsClient:{finalResult:async()=>({final:false})},simulations:20});await rt.pilot.setEnabled(false);const r=await rt.processCard(card(),{force:true});assert.equal(r.skipped,true);assert.equal(r.reason,'pilot paused');assert.equal(calls,0);assert.equal(r.aegis_weight,0);});
