'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const mod=()=>import('file://'+path.resolve(root,'public/gametwin-broadcast-experience.mjs'));

test('v2.0 broadcast experience exposes explicit presentation-only version',async()=>{const x=await mod();assert.equal(x.GAMETWIN_BROADCAST_EXPERIENCE_VERSION,'2.0.0');const s=x.broadcastExperienceSummary();assert.equal(s.presentation_only,true);assert.equal(s.predictive_authority,false);assert.equal(s.calibrated_live_win_probability,false);});

test('v2.0 pitch-location overlay maps pitches into bounded broadcast coordinates',async()=>{const x=await mod();const z=x.pitchLocationOverlay({plate_x:.2,plate_z:2.7,velocity_mph:96.4,name:'4-Seam Fastball'});assert.ok(z.x>0&&z.x<1);assert.ok(z.y>0&&z.y<1);assert.equal(z.in_visual_strike_zone,true);assert.ok(z.zone_cell>=1&&z.zone_cell<=9);assert.equal(z.predictive_authority,false);});

test('v2.0 pitch-location overlay keeps misses visible without turning them into model outputs',async()=>{const x=await mod();const z=x.pitchLocationOverlay({plate_x:1.45,plate_z:4.1,velocity_mph:87.1,name:'Slider'});assert.equal(z.in_visual_strike_zone,false);assert.equal(z.zone_cell,null);assert.equal(z.presentation_only,true);});

test('v2.0 SIM STATE EST is explicitly not calibrated live win probability',async()=>{const x=await mod();const e={inning:8,half:'top',score:{away:5,home:3},bases_after:['A',null,null],outs_after:1};const s=x.stateSwing(e,.54,.54);assert.ok(s.after_away>.54);assert.equal(s.label,'SIM STATE EST.');assert.equal(s.calibrated_live_wp,false);assert.equal(s.betting_model_input,false);assert.equal(s.predictive_authority,false);});

test('v2.0 lower thirds and transition packages cover PA inning and bullpen moments',async()=>{const x=await mod();const pa=x.lowerThirdForEvent({kind:'plate_appearance',inning:7,half:'top',batter:'Demo Batter',pitcher:'Demo Pitcher'},'pre');assert.equal(pa.eyebrow,'AT BAT');const inn=x.transitionPackage({kind:'half_inning',inning:7,half:'bottom',score:{away:4,home:3}},{away:'ATL',home:'NYM'});assert.equal(inn.kind,'inning');assert.match(inn.title,/BOTTOM 7TH/);const bp=x.transitionPackage({kind:'pitching_change',inning:8,half:'top',pitcher:'Demo RP',score:{away:4,home:3}},{away:'ATL',home:'NYM'});assert.equal(bp.kind,'bullpen');assert.equal(bp.exit_camera,'pitcher');});

test('v2.0 replay graphic and between-PA cuts remain presentation metadata',async()=>{const x=await mod();const g=x.replayGraphic({label:'Contact',speed:.48},{outcome:'HR'});assert.equal(g.bug,'INSTANT REPLAY');assert.equal(g.presentation_only,true);const c=x.betweenPACut({kind:'plate_appearance',outcome:'HR',leverage:.9,scored:['A']});assert.equal(c.camera,'dugout');assert.ok(c.hold_ms>0);});

test('v2.0 broadcast payload carries pregame baseline and experience capability without claiming live WP',()=>{const b=require('../src/gametwin-broadcast');const row={win_probability:{away:.57,home:.43},broadcast_context:{gamePk:1,date:'2026-09-04T23:00:00Z',venue:{name:'Park',field:{}},weather:{},away:{name:'Away',lineup:[],starter:{name:'A',arsenal:[]},bullpen:[]},home:{name:'Home',lineup:[],starter:{name:'H',arsenal:[]},bullpen:[]}},representative_game:{final:{away:0,home:0},play_by_play:[]}};const out=b.buildBroadcast(row),c=out.capabilities;assert.equal(out.version,'2.1.0-deployment-readiness');assert.equal(out.pregame_win_probability.away,.57);assert.equal(c.broadcast_experience_version,'2.0.0');assert.equal(c.representative_state_probability_estimate,true);assert.equal(c.calibrated_live_win_probability,false);assert.equal(c.broadcast_lower_thirds,true);assert.equal(c.pitch_location_overlay,true);assert.equal(out.presentation_only,true);});

test('v2.0 hosted renderer wires broadcast experience events without predictive authority',()=>{const s=read('public/gametwin-3d.mjs');assert.match(s,/gametwin-broadcast-experience\.mjs\?v=2\.0\.0/);for(const token of ['gametwin:pitch-location','gametwin:contact-card','gametwin:lower-third','gametwin:state-estimate','gametwin:broadcast-moment-start','gametwin:between-pa-cut'])assert.match(s,new RegExp(token));assert.doesNotMatch(s,/release_eligible\s*=\s*true|aegis_weight\s*=\s*[1-9]/);});

test('v2.0 WATCH UI includes TV-style overlays and labels state estimate honestly',()=>{const s=read('public/gametwin-production-ui.js'),css=read('public/gametwin-production.css');for(const token of ['gtpPitchLocator','gtpLowerThird','gtpStateSwing','SIM STATE EST.','NOT LIVE WP','gtpReplayRibbon','gtpBreakCard'])assert.match(s,new RegExp(token));for(const token of ['gtp-pitch-locator','gtp-lower-third','gtp-state-swing','gtp-replay-ribbon','gtp-break-card'])assert.match(css,new RegExp(token));});

test('v2.0 lab and loader expose Broadcast Experience while preserving visual subsystem provenance',()=>{const html=read('public/gametwin.html'),loader=read('public/gametwin-3d-loader.js');assert.match(html,/GameTwin v2\.1\.0 Deployment-Ready Shadow Lab/);assert.match(loader,/broadcast_experience:'2\.0\.0'/);assert.match(loader,/visual_fidelity:'1\.9\.0'/);assert.match(loader,/broadcast_director:'1\.9\.0'/);});
