'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');const {spawnSync}=require('node:child_process');
const root=path.join(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');const mod=()=>import('file://'+path.resolve(root,'public/gametwin-readiness.mjs'));

test('v2.1 viewport profiles separate compact portrait and short landscape',async()=>{const x=await mod();assert.equal(x.GAMETWIN_READINESS_VERSION,'2.1.0');assert.equal(x.viewportProfile({width:390,height:844}).id,'compact_portrait');assert.equal(x.viewportProfile({width:740,height:390}).id,'short_landscape');assert.equal(x.viewportProfile({width:1200,height:800}).id,'desktop');});

test('v2.1 overlay plan suppresses conflicting HUD during replay and break cards',async()=>{const x=await mod();const replay=x.overlayLayoutPlan({width:390,height:844},{replay:true,pitch:true,lower:true,state:true,telemetry:true});assert.equal(replay.density,'replay');assert.equal(replay.suppress.pitch,true);assert.equal(replay.suppress.lower,true);assert.equal(replay.suppress.state,true);const br=x.overlayLayoutPlan({width:740,height:390},{break:true,controls:true,telemetry:true});assert.equal(br.density,'transition');assert.equal(br.suppress.controls,true);assert.equal(br.predictive_authority,false);});

test('v2.1 short-landscape plan preserves one primary contextual overlay',async()=>{const x=await mod();const p=x.overlayLayoutPlan({width:740,height:390},{pitch:true,telemetry:true,lower:true,state:true});assert.equal(p.profile.id,'short_landscape');assert.equal(p.suppress.pitch,true);assert.equal(p.suppress.state,true);assert.equal(p.presentation_only,true);});

test('v2.1 frame monitor reports advisory grades and never auto changes quality',async()=>{const x=await mod();const m=x.createFramePerformanceMonitor({windowSize:60,emitEvery:10,minSamples:5,quality:'high'});let out=null,t=0;for(let i=0;i<30;i++){t+=50;out=m.frame(t)||out;}const s=out||m.snapshot();assert.equal(s.grade,'RED');assert.equal(s.recommended_quality,'medium');assert.equal(s.auto_quality_change,false);assert.equal(s.predictive_authority,false);});

test('v2.1 asset and deployment readiness retain shadow firewall',async()=>{const x=await mod();const a=x.assetReadiness({configured:{batter:true},loaded:{batter:{}},failures:[],warnings:[]});assert.equal(a.grade,'GREEN');const d=x.deploymentReadiness({tests_passed:true,asset_status:{configured:{batter:true},loaded:{batter:{}},failures:[]},performance:{grade:'GREEN'},aegis_weight:0,release_eligible:false,webgl:'READY'});assert.equal(d.ready,true);assert.equal(d.shadow_firewall,true);assert.equal(d.predictive_authority,false);const bad=x.deploymentReadiness({tests_passed:true,aegis_weight:.1,release_eligible:false});assert.equal(bad.ready,false);assert.ok(bad.blockers.includes('shadow_firewall_changed'));});

test('v2.1 hosted renderer wires performance and WebGL readiness telemetry',()=>{const s=read('public/gametwin-3d.mjs');assert.match(s,/createFramePerformanceMonitor/);assert.match(s,/gametwin:performance-sample/);assert.match(s,/webglcontextlost/);assert.match(s,/webglcontextrestored/);assert.match(s,/gametwin:webgl-context/);assert.doesNotMatch(s,/release_eligible\s*=\s*true|aegis_weight\s*=\s*[1-9]/);});

test('v2.1 production HUD includes collision-safe profiles and reduced-motion support',()=>{const ui=read('public/gametwin-production-ui.js'),css=read('public/gametwin-production.css');assert.match(ui,/gametwin-readiness\.mjs\?v=2\.1\.0/);assert.match(ui,/overlayLayoutPlan/);assert.match(ui,/data\.gtpViewport|dataset\.gtpViewport/);assert.match(css,/short_landscape|data-overlay-density/);assert.match(css,/max-height:520px/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/gtp-replay-active/);});

test('v2.1 deployment verifier passes bundled local package and checks shadow-only contract',()=>{const r=spawnSync(process.execPath,['scripts/verify-deployment-readiness.js'],{cwd:root,encoding:'utf8'});assert.equal(r.status,0,r.stderr||r.stdout);const out=JSON.parse(r.stdout);assert.equal(out.ok,true);assert.equal(out.version,'2.1.0');assert.equal(out.asset_urls,27);assert.equal(out.aegis_weight,0);assert.equal(out.release_eligible,false);});
