'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const os=require('node:os'); const path=require('node:path');
process.env.AEGIS_DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'aegis-ncaaf-')); delete process.env.SUPABASE_URL; delete process.env.SUPABASE_SECRET_KEY;
process.env.NCAAF_SIM_ENABLED='true'; process.env.NCAAF_SIM_SHADOW_ONLY='true'; process.env.AEGIS_NEW_ENGINE_AUTO_RELEASE='false';
const adapter=require('../src/sport-engines/adapters/ncaaf-adapter'); const shadow=require('../src/shadow-service'); const store=require('../src/store'); const safety=require('../src/deployment-safety');
function blind(overrides={}) { return {sport:'americanfootball_ncaaf',engine_version:adapter.INTERNAL_CHAMPION,game_id:'ncaaf-1',generated_at:'2026-09-10T12:00:00Z',game:{id:'ncaaf-1',home:'Georgia',away:'Clemson',start_time:'2026-09-12T16:00:00Z'},blind_features:['power_rating','net_epa_per_play','qb_continuity'],projection:{projected_score:{home:31,away:24},margin:7,total:55,moneyline_probabilities:{home:.68,away:.32},period_probabilities:{first_half:{margin:4,total:29,independent_model:true}},percentiles:{margin:{p10:-10,p50:7,p90:25}}},quality:{data_quality_score:.82,data_quality_grade:'B',uncertainty:1.2,model_dispersion:3.2,ensemble_agreement:'MODERATE',structural_break:false,early_season_high_uncertainty:false},diagnostics:{sport_specific:{ncaaf:{garbage_time:{assessed:true}}}},...overrides}; }
const market={captured_at:'2026-09-10T12:05:00Z',challenger_projection:{margin:3,total:52},current_price:{home_spread:-3,total_line:52},decision_status:'CORE_CANDIDATE',execution_status:'BET_NOW'};

test('NCAAF adapter is research-only and keeps market post-blind',()=>{const row=adapter.adapt(blind(),{market}); assert.equal(row.decision.status,'PASS'); assert.equal(row.governance.market_challenger_is_post_model,true); assert.equal(row.governance.production_promotion_allowed,false); assert.equal(row.governance.disagreement_firewall.thresholds_validated,false); assert.equal(row.market.post_model_projection.calibration_status,'UNCALIBRATED_RESEARCH'); assert.equal(row.projection.period_probabilities.first_half.independent_model,true);});
test('NCAAF blind rejects leakage, future results, and market-before-blind',()=>{assert.throws(()=>adapter.adapt(blind({sportsbook_spread:-3}),{market}),/hygiene/); assert.throws(()=>adapter.adapt(blind({final_score:{home:31,away:24}}),{market}),/hygiene/); assert.throws(()=>adapter.adapt(blind(),{market:{...market,captured_at:'2026-09-10T11:59:00Z'}}),/after immutable blind/);});
test('early uncertainty, dispersion and large favorites remain PASS',()=>{for(const changed of [{early_season_high_uncertainty:true},{model_dispersion:8}]){const row=adapter.adapt(blind({quality:{...blind().quality,...changed}}),{market}); assert.equal(row.governance.disagreement_firewall.status,'RESEARCH_PASS');} const missing=blind(); delete missing.projection.period_probabilities.first_half; assert.equal(adapter.adapt(missing,{market:{...market,current_price:{home_spread:-29,total_line:58}}}).decision.status,'PASS');});
test('durable NCAAF archive is immutable and empty cache persistence is sport-isolated',async()=>{const first=await shadow.ingest({sport:'americanfootball_ncaaf',engine_output:blind(),market}); assert.equal(first.record.release_status,'SHADOW_ONLY'); assert.equal(first.record.official_final_card_eligible,false); const same=await shadow.ingest({sport:'americanfootball_ncaaf',engine_output:blind(),market}); assert.equal(same.duplicate,true); await assert.rejects(()=>shadow.ingest({sport:'americanfootball_ncaaf',engine_output:blind({generated_at:'2026-09-10T12:01:00Z'}),market}),/immutable/); store.resetMemory(); const loaded=await shadow.listBlinds({sport:'americanfootball_ncaaf'}); assert.equal(loaded.count,1); assert.equal(loaded.current_champion,adapter.INTERNAL_CHAMPION); const state=await store.load(); assert.deepEqual(state.latest_cards,{}); assert.equal(state.audit.length,0);});
test('NCAAF grading is idempotent and cannot enter official accounting',async()=>{const result={game_id:'ncaaf-1',home_score:31,away_score:21,completed_at:'2026-09-12T20:00:00Z'}; const one=await shadow.gradeMany({sport:'americanfootball_ncaaf',results:[result]}); assert.equal(one.graded.length,1); const two=await shadow.gradeMany({sport:'americanfootball_ncaaf',results:[result]}); assert.equal(two.skipped[0].reason,'ALREADY_GRADED'); assert.equal(one.graded[0].grade.official_results_eligible,false); assert.equal(one.graded[0].grade.official_bankroll_eligible,false);});
test('NCAAF staging configuration rejects production state and release paths',()=>{const env={AEGIS_DEPLOYMENT_ENV:'ncaaf-shadow-staging',AEGIS_STATE_ID:'ncaaf-shadow-staging',AEGIS_AUTOPILOT_ENABLED:'false',AEGIS_RELEASE_SPORTS:'none',NCAAF_SIM_ENABLED:'true',NCAAF_SIM_SHADOW_ONLY:'true',NFL_SIM_ENABLED:'false',MLB_SIM_ENABLED:'false',AEGIS_NEW_ENGINE_AUTO_RELEASE:'false'}; const identity=safety.assertStagingConfiguration(env); assert.equal(identity.ncaaf_shadow_staging,true); assert.equal(identity.production_release_allowed,false); assert.throws(()=>safety.assertStagingConfiguration({...env,AEGIS_STATE_ID:'main'}),/ncaaf-shadow-staging/); assert.throws(()=>safety.assertStagingConfiguration({...env,AEGIS_RELEASE_SPORTS:'americanfootball_ncaaf'}),/live sport/);});
test('staging blueprint is isolated and no NCAAF scheduler was registered on main',()=>{const root=path.resolve(__dirname,'..'); const yaml=fs.readFileSync(path.join(root,'render-ncaaf-shadow-staging.yaml'),'utf8'); assert.match(yaml,/branch: ncaaf-shadow-staging/); assert.match(yaml,/AEGIS_STATE_ID\s+value: ncaaf-shadow-staging/); assert.match(yaml,/NCAAF_SIM_ENABLED\s+value: "true"/); assert.match(yaml,/AEGIS_AUTOPILOT_ENABLED\s+value: "false"/); assert.equal(fs.existsSync(path.join(root,'.github/workflows/ncaaf-shadow-scheduler.yml')),false);});
