'use strict';

const crypto=require('crypto');
const market=require('./gametwin-market');

const VERSION='0.4.0-calibration-audit';
const SCHEMA_VERSION=1;

function round(x,n=6){if(x===null||x===undefined||!Number.isFinite(Number(x)))return null;const p=10**n;return Math.round(Number(x)*p)/p;}
function isoNow(){return new Date().toISOString();}
function hashId(parts){return crypto.createHash('sha256').update(parts.map(x=>String(x??'')).join('|')).digest('hex').slice(0,24);}
function clampProb(p){return Math.max(1e-6,Math.min(1-1e-6,Number(p)));}
function brier(prob,outcome){if(!Number.isFinite(Number(prob))||![0,1].includes(outcome))return null;return round((Number(prob)-outcome)**2,8);}
function logLoss(prob,outcome){if(!Number.isFinite(Number(prob))||![0,1].includes(outcome))return null;const p=clampProb(prob);return round(-(outcome*Math.log(p)+(1-outcome)*Math.log(1-p)),8);}
function forecastKey(quote={}){const m=String(quote.market||'').toLowerCase(),player=market.normalizeName(quote.player||quote.name||quote.selection_name||''),sel=market.normalizeName(quote.selection||''),point=Number.isFinite(Number(quote.point))?Number(quote.point):'';return `${m}|${player}|${sel}|${point}`;}
function eventFamily(quote={}){const m=String(quote.market||'').toLowerCase();if(['h2h','moneyline','ml'].includes(m))return 'moneyline';if(['spread','spreads','run_line','runline'].includes(m))return 'run_line';if(['total','totals','game_total'].includes(m))return 'total';if(m.startsWith('pitcher_'))return 'pitcher_prop';if(m.startsWith('player_')||m.startsWith('batter_')||['hits','total_bases','home_runs','runs'].includes(m))return 'batter_prop';return m||'unknown';}
function projectionCore(projection={}){return {version:projection.version,simulations:projection.simulations,teams:projection.teams,projected_score:projection.projected_score,win_probability:projection.win_probability,fair_moneyline:projection.fair_moneyline,data_quality:projection.data_quality,integration:projection.integration};}
function builtInForecasts(projection={}){const out=[];const add=(key,family,prob)=>{if(Number.isFinite(Number(prob)))out.push({forecast_key:key,family,source:'gametwin',fair_probability:Number(prob),quote:null});};add('builtin|home_win','moneyline',projection?.win_probability?.home);add('builtin|home_minus_1_5','run_line',projection?.markets?.home_minus_1_5);add('builtin|over_8_5','total',projection?.markets?.over_8_5);add('builtin|over_9_5','total',projection?.markets?.over_9_5);return out;}
function attachAegisProbability(row,aegisForecasts){if(!aegisForecasts)return row;const v=typeof aegisForecasts==='function'?aegisForecasts(row):aegisForecasts[row.forecast_key];const p=Number(v?.probability??v);return Number.isFinite(p)?{...row,aegis_probability:round(p,6)}:row;}
function createSnapshot({spec,projection,quotes=[],aegisForecasts=null,capturedAt=null,book=null,metadata={}}={}){
  if(!spec?.gamePk)throw new Error('GameTwin audit snapshot requires spec.gamePk');if(!projection?.simulations)throw new Error('GameTwin audit snapshot requires a simulation projection');
  const evaluated=market.evaluateBoard(projection,quotes),priced=evaluated.filter(r=>r.supported).map(r=>attachAegisProbability({forecast_key:`quote|${forecastKey(r.quote)}`,family:eventFamily(r.quote),source:'gametwin',fair_probability:r.fair_probability,win_probability:r.win_probability,lose_probability:r.lose_probability,push_probability:r.push_probability,fair_price:r.fair_price,book_implied_probability:r.book_implied_probability,market_devig_probability:r.market_devig_probability??null,raw_probability_edge:r.raw_probability_edge,devig_edge:r.devig_edge??null,estimated_ev:r.estimated_ev,quote:r.quote,projection_person:r.projection_person??null,metric:r.metric??null},aegisForecasts));
  const built=builtInForecasts(projection).map(r=>attachAegisProbability(r,aegisForecasts));const captured=capturedAt||isoNow();
  return {schema_version:SCHEMA_VERSION,version:VERSION,snapshot_id:hashId([spec.gamePk,captured,projection.version,projection.simulations,book||'']),captured_at:captured,gamePk:Number(spec.gamePk),game_date:spec.date||null,book:book||null,teams:{away:spec.away?.name||projection.teams?.away,home:spec.home?.name||projection.teams?.home},venue:spec.venue?.name||null,data_quality:spec.data_quality||projection.data_quality||null,matchup_intelligence:spec.matchup_intelligence||null,projection:projectionCore(projection),forecasts:[...built,...priced],metadata:{...metadata,shadow_only:true},integration:{aegis_weight:0,release_eligible:false,mode:'shadow',automatic_weight_changes:false}};
}
function findActualPerson(result,group,name){for(const side of ['away','home'])for(const [n,row] of Object.entries(result?.[group]?.[side]||{}))if(market.sameName(n,name))return {name:n,side,row};return null;}
function gradeGameQuote(result,q){const m=String(q.market||'').toLowerCase(),sel=String(q.selection||'').toLowerCase(),away=result.score.away,home=result.score.home;let z=null;
  const side=market.sameName(q.selection,result.teams?.home?.name)||sel==='home'?'home':market.sameName(q.selection,result.teams?.away?.name)||sel==='away'?'away':null;
  if(['h2h','moneyline','ml'].includes(m)){if(!side)return null;z=side==='home'?home-away:away-home;}
  else if(['spread','spreads','run_line','runline'].includes(m)){if(!side||!Number.isFinite(Number(q.point)))return null;z=(side==='home'?home-away:away-home)+Number(q.point);}
  else if(['total','totals','game_total'].includes(m)){if(!['over','under'].includes(sel)||!Number.isFinite(Number(q.point)))return null;z=home+away-Number(q.point);if(sel==='under')z=-z;}
  else return null;return z>1e-9?'WIN':z<-1e-9?'LOSS':'PUSH';
}
const ACTUAL_METRIC={
  player_hits:['players','H'],hits:['players','H'],player_total_bases:['players','TB'],total_bases:['players','TB'],player_home_runs:['players','HR'],home_runs:['players','HR'],player_runs:['players','R'],runs:['players','R'],player_strikeouts:['players','K'],batter_strikeouts:['players','K'],player_walks:['players','BB'],batter_walks:['players','BB'],
  pitcher_strikeouts:['pitchers','K'],pitcher_ks:['pitchers','K'],pitcher_outs:['pitchers','OUTS'],pitcher_outs_recorded:['pitchers','OUTS'],pitcher_earned_runs:['pitchers','ER'],pitcher_er:['pitchers','ER'],pitcher_hits_allowed:['pitchers','H'],pitcher_walks:['pitchers','BB'],pitcher_home_runs_allowed:['pitchers','HR'],pitcher_pitches:['pitchers','PITCHES']
};
function gradePropQuote(result,q){const cfg=ACTUAL_METRIC[String(q.market||'').toLowerCase()];if(!cfg)return null;const found=findActualPerson(result,cfg[0],q.player||q.name||q.selection_name);if(!found||!Number.isFinite(Number(q.point)))return null;const value=Number(found.row?.[cfg[1]]),sel=String(q.selection||'over').toLowerCase();if(!Number.isFinite(value)||!['over','under'].includes(sel))return null;let z=value-Number(q.point);if(sel==='under')z=-z;return {outcome:z>1e-9?'WIN':z<-1e-9?'LOSS':'PUSH',actual_value:value,actual_person:found.name,metric:cfg[1]};}
function gradeQuote(result,q){const prop=ACTUAL_METRIC[String(q.market||'').toLowerCase()]?gradePropQuote(result,q):null;if(prop)return prop;const outcome=gradeGameQuote(result,q);return outcome?{outcome}:null;}
function unitReturn(price,outcome){if(outcome==='PUSH')return 0;if(outcome==='LOSS')return -1;if(outcome!=='WIN')return null;return market.americanProfit(price);}
function gradeBuiltIn(result,key){const h=result.score.home,a=result.score.away;if(key==='builtin|home_win')return h>a?'WIN':h<a?'LOSS':'PUSH';if(key==='builtin|home_minus_1_5')return h-a>1.5?'WIN':'LOSS';if(key==='builtin|over_8_5')return h+a>8.5?'WIN':'LOSS';if(key==='builtin|over_9_5')return h+a>9.5?'WIN':'LOSS';return null;}
function closingGroupKey(q={}){const m=String(q.market||'').toLowerCase(),player=market.normalizeName(q.player||q.name||q.selection_name||''),point=Number.isFinite(Number(q.point))?Number(q.point):'';return `${m}|${player}|${point}`;}
function closingMarketProbabilities(quotes=[]){const groups=new Map(),out=new Map();for(const q of quotes){const key=closingGroupKey(q);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(q);}for(const rows of groups.values()){if(rows.length!==2)continue;const d=market.twoWayDevig(rows[0].price,rows[1].price);if(!d)continue;out.set(forecastKey(rows[0]),d.a);out.set(forecastKey(rows[1]),d.b);}return out;}
function gradeSnapshot(snapshot,result,{closingQuotes=[]}={}){
  if(!snapshot?.snapshot_id)throw new Error('GameTwin grading requires a snapshot');if(!result?.final)return {...snapshot,grade:{status:'PENDING',checked_at:isoNow(),result_status:result?.status||null}};
  const closeMap=new Map(closingQuotes.map(q=>[forecastKey(q),q])),closeDevig=closingMarketProbabilities(closingQuotes);const graded=[];
  for(const row of snapshot.forecasts||[]){let detail;if(row.quote)detail=gradeQuote(result,row.quote);else{const o=gradeBuiltIn(result,row.forecast_key);detail=o?{outcome:o}:null;}if(!detail){graded.push({...row,grade_status:'UNGRADABLE'});continue;}const outcome=detail.outcome,binary=outcome==='WIN'?1:outcome==='LOSS'?0:null,entryProb=row.market_devig_probability??row.book_implied_probability??null,close=row.quote?closeMap.get(forecastKey(row.quote)):null,closeImplied=close?market.americanToProb(close.price):null,closeFair=row.quote?closeDevig.get(forecastKey(row.quote)):null;graded.push({...row,grade_status:'GRADED',outcome,...detail,brier:brier(row.fair_probability,binary),log_loss:logLoss(row.fair_probability,binary),aegis_brier:brier(row.aegis_probability,binary),aegis_log_loss:logLoss(row.aegis_probability,binary),market_brier:brier(entryProb,binary),market_log_loss:logLoss(entryProb,binary),closing_market_brier:brier(closeFair??closeImplied,binary),closing_market_log_loss:logLoss(closeFair??closeImplied,binary),unit_return:row.quote?round(unitReturn(row.quote.price,outcome),6):null,closing_price:close?Number(close.price):null,closing_implied_probability:closeImplied==null?null:round(closeImplied,6),closing_devig_probability:closeFair==null?null:round(closeFair,6),raw_clv_probability:closeImplied==null||row.book_implied_probability==null?null:round(closeImplied-row.book_implied_probability,6),devig_clv_probability:closeFair==null||row.market_devig_probability==null?null:round(closeFair-row.market_devig_probability,6)});}
  const scoreError={home:round(Math.abs(Number(snapshot.projection?.projected_score?.home)-Number(result.score.home)),3),away:round(Math.abs(Number(snapshot.projection?.projected_score?.away)-Number(result.score.away)),3),total:round(Math.abs(Number(snapshot.projection?.projected_score?.total)-(Number(result.score.home)+Number(result.score.away))),3)};
  return {...snapshot,grade:{status:'FINAL',graded_at:isoNow(),result:{gamePk:result.gamePk,score:result.score,teams:result.teams,status:result.status},score_error:scoreError,forecasts:graded}};
}
function mean(xs){const v=xs.filter(x=>x!==null&&x!==undefined&&x!==''&&Number.isFinite(Number(x))).map(Number);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null;}
function calibrationBuckets(rows,width=.1){const bins=new Map();for(const r of rows){const p=Number(r.fair_probability),y=r.outcome==='WIN'?1:r.outcome==='LOSS'?0:null;if(!Number.isFinite(p)||y===null)continue;const lo=Math.min(.9,Math.floor(p/width)*width),key=lo.toFixed(1);if(!bins.has(key))bins.set(key,{low:lo,high:Math.min(1,lo+width),n:0,sum_p:0,wins:0});const b=bins.get(key);b.n++;b.sum_p+=p;b.wins+=y;}return [...bins.values()].sort((a,b)=>a.low-b.low).map(b=>({low:round(b.low,2),high:round(b.high,2),n:b.n,mean_forecast:round(b.sum_p/b.n,4),observed_rate:round(b.wins/b.n,4),calibration_error:round(Math.abs(b.sum_p/b.n-b.wins/b.n),4)}));}
function summarizeGroup(rows){const binary=rows.filter(r=>['WIN','LOSS'].includes(r.outcome)),priced=rows.filter(r=>r.quote&&['WIN','LOSS','PUSH'].includes(r.outcome)),returns=priced.map(r=>r.unit_return).filter(Number.isFinite),wins=rows.filter(r=>r.outcome==='WIN').length,losses=rows.filter(r=>r.outcome==='LOSS').length,pushes=rows.filter(r=>r.outcome==='PUSH').length;return {n:rows.length,binary_n:binary.length,wins,losses,pushes,win_rate:binary.length?round(wins/binary.length,4):null,brier:round(mean(binary.map(r=>r.brier)),6),log_loss:round(mean(binary.map(r=>r.log_loss)),6),aegis_brier:round(mean(binary.map(r=>r.aegis_brier)),6),market_brier:round(mean(binary.map(r=>r.market_brier)),6),closing_market_brier:round(mean(binary.map(r=>r.closing_market_brier)),6),roi:returns.length?round(returns.reduce((a,b)=>a+b,0)/returns.length,6):null,total_units:returns.length?round(returns.reduce((a,b)=>a+b,0),4):null,avg_raw_clv_probability:round(mean(priced.map(r=>r.raw_clv_probability)),6),avg_devig_clv_probability:round(mean(priced.map(r=>r.devig_clv_probability)),6),calibration:calibrationBuckets(binary)};}
function comparisonSummary(rows){const commonAegis=rows.filter(r=>Number.isFinite(r.brier)&&Number.isFinite(r.aegis_brier)),commonMarket=rows.filter(r=>Number.isFinite(r.brier)&&Number.isFinite(r.closing_market_brier)),gtA=mean(commonAegis.map(r=>r.brier)),ae=mean(commonAegis.map(r=>r.aegis_brier)),gtM=mean(commonMarket.map(r=>r.brier)),mk=mean(commonMarket.map(r=>r.closing_market_brier));return {vs_aegis:{n:commonAegis.length,gametwin_brier:round(gtA,6),aegis_brier:round(ae,6),delta:gtA==null||ae==null?null:round(gtA-ae,6),better:gtA==null||ae==null?null:gtA<ae},vs_closing_market:{n:commonMarket.length,gametwin_brier:round(gtM,6),closing_market_brier:round(mk,6),delta:gtM==null||mk==null?null:round(gtM-mk,6),better:gtM==null||mk==null?null:gtM<mk}};}
function summarizeAudit(gradedSnapshots=[]){const finals=gradedSnapshots.filter(s=>s?.grade?.status==='FINAL'),rows=finals.flatMap(s=>s.grade.forecasts||[]).filter(r=>r.grade_status==='GRADED'),groups={};for(const family of [...new Set(rows.map(r=>r.family))])groups[family]=summarizeGroup(rows.filter(r=>r.family===family));const scoreHome=mean(finals.map(s=>s.grade.score_error?.home)),scoreAway=mean(finals.map(s=>s.grade.score_error?.away)),scoreTotal=mean(finals.map(s=>s.grade.score_error?.total));return {version:VERSION,snapshots:gradedSnapshots.length,final_games:finals.length,forecasts:rows.length,overall:summarizeGroup(rows),by_family:groups,comparisons:comparisonSummary(rows),score_mae:{home:round(scoreHome,4),away:round(scoreAway,4),team_run_average:round(mean([scoreHome,scoreAway]),4),total:round(scoreTotal,4)},governance:weightReadiness(finals,rows)};}
function weightReadiness(finals,rows){const binary=rows.filter(r=>['WIN','LOSS'].includes(r.outcome)),families={};for(const f of [...new Set(binary.map(r=>r.family))])families[f]=binary.filter(r=>r.family===f).length;const gameFloor=50,overallFloor=200,familyFloor=75,eligibleFamilies=Object.entries(families).filter(([,n])=>n>=familyFloor).map(([f])=>f),sampleReady=finals.length>=gameFloor&&binary.length>=overallFloor&&eligibleFamilies.length>0;return {status:sampleReady?'REVIEW_READY':'COLLECTING',minimum_final_games:gameFloor,minimum_binary_forecasts:overallFloor,minimum_family_forecasts:familyFloor,current_final_games:finals.length,current_binary_forecasts:binary.length,family_counts:families,eligible_families:eligibleFamilies,automatic_weight_change:false,aegis_weight:0,note:'Meeting sample floors only permits human/model review. It never automatically gives GameTwin betting authority.'};}

module.exports={VERSION,SCHEMA_VERSION,createSnapshot,gradeSnapshot,summarizeAudit,weightReadiness,brier,logLoss,calibrationBuckets,forecastKey,eventFamily,gradeQuote,gradeGameQuote,gradePropQuote,unitReturn,closingMarketProbabilities,comparisonSummary};
